---
name: Object-Lazy
version: 0.05
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
abstract: 'Object::Lazy - create objects late from non-owned classes'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Params::Validate: 0
  perl: 5.006001
build_requires:
  Test::NoWarnings: 0
  Test::Simple: 0
recommends:
  Test::More: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
provides:
  Object::Lazy:
    file: lib/Object/Lazy.pm
    version: 0.05
  Object::Lazy::Ref:
    file: lib/Object/Lazy/Ref.pm
    version: 0.01
  Object::Lazy::Validate:
    file: lib/Object/Lazy/Validate.pm
    version: 0.01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
