---
abstract: 'Object::Lazy - create objects late from non-owned classes'
author:
  - 'Steffen Winkler <steffenw at cpan.org>'
build_requires:
  Cwd: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Lazy
provides:
  Object::Lazy:
    file: lib/Object/Lazy.pm
    version: 0.07
  Object::Lazy::Ref:
    file: lib/Object/Lazy/Ref.pm
    version: 0.01
  Object::Lazy::Validate:
    file: lib/Object/Lazy/Validate.pm
    version: 0.01
recommends:
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  Carp: 0
  English: 0
  Params::Validate: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
