---
name: Object-Lazy
version: 0.02
author:
  - 'Steffen Winkler - steffenw@cpan.org'
abstract: create objects late from non-owned classes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  English: 0
  Params::Validate: 0
build_requires:
  Test::More: 0
provides:
  Object::Lazy:
    file: lib/Object/Lazy.pm
    version: 0.02
  Object::Lazy::Ref:
    file: lib/Object/Lazy/Ref.pm
    version: 0.01
  Object::Lazy::Validate:
    file: lib/Object/Lazy/Validate.pm
    version: 0.01
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
